- name: Install Node.js and npm using NVM
  shell: >-
    wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
    && export NVM_DIR="{{ nvm_dir }}"
    && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    && nvm install --lts
    && nvm use --lts
  args:
    creates: "{{ nvm_dir }}/nvm.sh"
  when: node_check.rc != 0 or npm_check.rc != 0

- name: Add NVM to .bashrc
  lineinfile:
    path: "/root/.bashrc"
    line: "{{ item }}"
  loop:
    - 'export NVM_DIR="{{ nvm_dir }}"'
    - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
    - '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"'
  when: node_check.rc != 0 or npm_check.rc != 0

- name: Reload .bashrc
  shell: source /root/.bashrc
  args:
    executable: /bin/bash
  when: node_check.rc != 0 or npm_check.rc != 0

- name: Verify Node.js installation
  shell: . {{ nvm_dir }}/nvm.sh && node --version
  register: node_version
  changed_when: false
  args:
    executable: /bin/bash

- name: Verify npm installation
  shell: . {{ nvm_dir }}/nvm.sh && npm --version
  register: npm_version
  changed_when: false
  args:
    executable: /bin/bash

- name: Display Node.js and npm versions
  debug:
    msg:
      - "Node.js version: {{ node_version.stdout }}"
      - "npm version: {{ npm_version.stdout }}"
