services:
  proxy-demo:
    restart: unless-stopped
    image: "ghcr.io/squirrelcorporation/squirrelserversmanager-proxy:latest"
    ports:
      - "8000:8000"
    depends_on:
      - client
      - server
  server:
    restart: unless-stopped
    image: "ghcr.io/squirrelcorporation/squirrelserversmanager-server-demo:master"
  client:
    restart: unless-stopped
    depends_on:
      - server
    image: "ghcr.io/squirrelcorporation/squirrelserversmanager-client:latest"

