- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install required packages for Docker (Debian-based)
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
  when: ansible_os_family == "Debian"

- name: Add Docker's official GPG key (Debian-based)
  ansible.builtin.shell: |
    sudo install -m 0755 -d /etc/apt/keyrings
    sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
    sudo chmod a+r /etc/apt/keyrings/docker.asc
  when: ansible_os_family == "Debian"

- name: Set up the Docker repository (Debian-based)
  ansible.builtin.shell: |
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
      $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable" |\
      sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  when: ansible_os_family == "Debian"

- name: Update apt package cache after adding Docker repo
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install required packages for Docker (RHEL-based)
  ansible.builtin.yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
  when: ansible_os_family == "RedHat"

- name: Add Docker's official repository (RHEL-based)
  ansible.builtin.command: |
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: ansible_os_family == "RedHat"

- name: Ensure old versions of Docker are not installed (Debian-based)
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc
  when: ansible_os_family == "Debian"

- name: Ensure old versions of Docker are not installed (RHEL-based)
  ansible.builtin.yum:
    name: "{{ item }}"
    state: absent
  loop:
    - docker
    - docker-common
    - docker-selinux
    - docker-engine
  when: ansible_os_family == "RedHat"

- name: Install Docker CE (Debian-based)
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Docker CE (RHEL-based)
  ansible.builtin.yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  when: ansible_os_family == "RedHat"

- name: Start and enable Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
