- name: Check if PM2 is installed
  shell: . {{ node_agent_nvm_dir }}/nvm.sh && npm list -g pm2
  register: pm2_check
  ignore_errors: true
  changed_when: false
  args:
    executable: /bin/bash

- name: Install "PM2" node.js package globally
  shell: . {{ node_agent_nvm_dir }}/nvm.sh && npm install -g pm2
  args:
    executable: /bin/bash
  when: pm2_check.rc != 0

- name: Install PM2 LogRotate
  shell: . {{ node_agent_nvm_dir }}/nvm.sh && pm2 install pm2-logrotate
  args:
    executable: /bin/bash

- name: Install PM2 on startup
  shell: . {{ node_agent_nvm_dir }}/nvm.sh && pm2 startup
  args:
    executable: /bin/bash

- name: Save Agent on startup
  shell: . {{ node_agent_nvm_dir }}/nvm.sh && pm2 save
  args:
    executable: /bin/bash

- name: Update PM2
  shell: . {{ node_agent_nvm_dir }}/nvm.sh && pm2 update
  args:
    executable: /bin/bash
