---
#  ,;;:;,
#   ;;;;;
#  ,:;;:;    ,'=.
#  ;:;:;' .=" ,'_\
#  ':;:;,/  ,__:=@
#   ';;:;  =./)_
#     `"=\_  )_"`
#          ``'"`
# Playbook Name: Reboot
# Description: This playbook reboots unconditionally a machine
# Module: SSM-CORE
# Tags: reboot, restart, host

- hosts: all
  tasks:
  - name: Unconditionally reboot the machine
    ansible.builtin.reboot:

