---
#  ,;;:;,
#   ;;;;;
#  ,:;;:;    ,'=.
#  ;:;:;' .=" ,'_\
#  ':;:;,/  ,__:=@
#   ';;:;  =./)_
#     `"=\_  )_"`
#          ``'"`
# Playbook Name: Check Device connectivity before adding
# Description: This playbook checks that the device is reachable, and can communicate with SSM API.
# Module: SSM-CORE
# Tags: installation, agent, ping, connectivity

- name: Check Device connectivity before adding
  hosts: all
  tasks:
    - name: Test Connection
      ping:
      timeout: 600
    - name: Check that you can connect (GET) to the API and it returns a status 200
      ansible.builtin.uri:
        url: "{{ _ssm_masterNodeUrl }}/api/ping"
