---
#  ,;;:;,
#   ;;;;;
#  ,:;;:;    ,'=.
#  ;:;:;' .=" ,'_\
#  ':;:;,/  ,__:=@
#   ';;:;  =./)_
#     `"=\_  )_"`
#          ``'"`
# Playbook Name: Restart Agent on Targeted Device
# Description: This playbook restart the agent on the targeted device based on the specified installation method.
# Module: SSM-CORE
# Tags: restart, agent, docker, node

- name: Restart agent on targeted device
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Validate installMethod variable
      fail:
        msg: "Invalid _ssm_installMethod value. Must be one of: 'node', 'node_enhanced_playbook', 'docker'."
      when: _ssm_installMethod not in valid_install_methods

    - name: Node Agent Restart
      include_role:
        name: restart_agent_node
      when: _ssm_installMethod == 'node' or _ssm_installMethod == 'node_enhanced_playbook'


    - name: Include role for docker installation
      include_role:
        name: install_agent_docker
      when: _ssm_installMethod == 'docker'
