- name: Ensure Docker Compose services are running
  community.docker.docker_compose_v2:
    project_src: "{{ docker_agent_docker_compose_dir }}"
    state: present
    recreate: always
    pull: always
    remove_orphans: yes

