---
- name: Define variables
  set_fact:
    base_path: "{{ node_agent_base_path }}"
    nvm_dir:  "{{ node_agent_nvm_dir }}"
    nvm_profile: "~/.bashrc"
    nvm_install: 'wget' # options are: wget, curl or git
    autocomplete: false
    nodejs_version: "lts"
    default: false
    ansible_user: 'root'

- include_tasks: debug.yml
- include_tasks: error_handling.yml
- include_tasks: shell_detection.yml
- include_tasks: nvm_install.yml
- include_tasks: node_install.yml
- include_tasks: pm2_install.yml
- include_tasks: git_checkout.yml
- include_tasks: npm_install.yml
- include_tasks: pm2_start.yml
- include_tasks: report_status.yml
