---
#  ,;;:;,
#   ;;;;;
#  ,:;;:;    ,'=.
#  ;:;:;' .=" ,'_\
#  ':;:;,/  ,__:=@
#   ';;:;  =./)_
#     `"=\_  )_"`
#          ``'"`
# Playbook Name: Create a docker volume
# Description: This playbook creates a Docker volume on the host by applying various parameters
# Module: SSM-CORE
# Tags: volume, storage, ip, docker

- name: Create Docker Volume
  hosts: all
  become: true
  vars:
    network_config:
      name: "{{ name }}"
  tasks:
    - name: Create a Docker volume
      community.docker.docker_volume:
        name: "{{ name }}"
        driver: local
        state: present
