---
#  ,;;:;,
#   ;;;;;
#  ,:;;:;    ,'=.
#  ;:;:;' .=" ,'_\
#  ':;:;,/  ,__:=@
#   ';;:;  =./)_
#     `"=\_  )_"`
#          ``'"`
# Playbook Name: Start a Docker compose stack
# Description: This playbook starts a docker compose stack
# Module: SSM-CORE
# Tags: docker, compose, stack, services

- name: Docker Compose
  hosts: all
  gather_facts: false

  tasks:
    - name: Present
      community.docker.docker_compose_v2:
        project_name: '{{ project }}'
        definition: '{{ definition | from_yaml }}'
        recreate: "always"
      register: output

    - name: Show results
      ansible.builtin.debug:
        var: output
