# .github/workflows/molecule.yml

name: Molecule Tests

on:
  push:
    paths:
      - 'server/src/tests/molecule/**'
      - 'server/src/ansible/**'
    branches: [ master ]
  pull_request:
    paths:
      - 'server/src/tests/molecule/**'
      - 'server/src/ansible/**'
    branches: [ master ]
  workflow_dispatch:

jobs:
  molecule-tests:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_ASYNC_DIR: "/tmp/.ansible_async"

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('server/src/tests/molecule/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Ansible and Molecule
        working-directory: server/src/tests/molecule
        run: |
          python -m pip install --upgrade pip
          pip install ansible molecule ansible-lint
          pip install -r requirements.txt

      - name: Debug folder structure
        working-directory: server/src/tests/molecule
        run: |
          echo "Listing directory contents:"
          ls -R

      - name: Ensure cache directory exists
        run: |
          mkdir -p /home/runner/.cache/molecule/tests/default/inventory

      - name: Run Molecule default scenario
        working-directory: server/src/tests/
        run: molecule test